spring.application.name=connectify

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.boot.allow_jdbc_metadata_access=false
#spring.jpa.hibernate.ddl-auto=none
#spring.jpa.show-sql=true
#spring.sql.init.mode=never
spring.jpa.hibernate.ddl-auto=none
spring.datasource.url=jdbc:mysql://connectify-kmaconnectify.h.aivencloud.com:13227/atbm
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_GX0h-33eqEF6YPGj6vi
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

JWT.SIGNER_KEY=AfdcYl9aSCrZIBFtDCLBXK1SabZXXlwgLipmmU1SDFx2+GFX0AfxUoDwEZt60/nG
JWT.ISSUER=kma.connectify
JWT.VALID_DURATION=604800
JWT.REFRESHABLE_DURATION=604800

S3.ACCESS_KEY=AKIA4ZARC2XS7VFHINDO
S3.SECRET_KEY=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
S3.BUCKET_NAME=kmaconnectify

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

CLIENT.URL=http://192.168.34.100:8081

RSA.PRIVATE_KEY=MIICXAIBAAKBgQCU3SNRPS8RadKvNMwd0RD8iFuQRoC99pv8n6OWu5KQyQo3ZQBIjVDBOwGxYQkd57O1eAoffr54/EcCiHgbAqlp9jR1osMHpmal0Sw8PtBXpZl1YYwTzi2tHU/OisvdvMkqXJgShfig2jPT11QDl0eHzI0Ux8vc1luJT+qZ/EiaMwIDAQABAoGAXP43zcwW1x3wSxsEV6v+nILiECK60fB4STvAiazrRh8QjsI9hxUgWVVvHUus0k2n6bjvOfWHLzUJdv+hZ94lzdwYsHB/jVm+iLfdCHJ1gyd4wb8dSFLqrN1lef34Hz7RwM1tc3/Rk29TU+/agVsOGUEJJFjBMjDmTfQhkMRnaYECQQD7N9MpB4zvMTJtKtN1fBxyf4CGTV6SZnEqL6HqTfifaV4tqXzONmutHm4ho6zznSzy9YO6fvoalZw5aLt/sCyRAkEAl7KLjpFMFbSlwBCDxx2el40OGDSuep19ezPWdputS0pW5/u14CWJL74b+pUK5IAh4KfQ3wsI/TO2PvR+k9sMgwJAELGV+5z/1Yk8Y5q78IutzEICxWnwxeO+02HU7Z/+zIEQ/BHONFnTb+6cvOmGfa3NJdwAw+zaK9gTSJFYHFUVsQJAN1zUDe39JJbPPy9HyK2IqaqzECZ53woHN6WNia/7KNUyrmtwzyMj1Ca/s04dsZMJyiG02xH979qlkohMgc2Z3QJBAPXxsHEGDU9tybHC3e6DOVU2WKWwUwupE6ZSHbWFMuODmvSzYBNQn/7l30IYs5WyNX6u8JHFpER71+RD5TNm5u8=
RSA.PUBLIC_KEY=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCU3SNRPS8RadKvNMwd0RD8iFuQRoC99pv8n6OWu5KQyQo3ZQBIjVDBOwGxYQkd57O1eAoffr54/EcCiHgbAqlp9jR1osMHpmal0Sw8PtBXpZl1YYwTzi2tHU/OisvdvMkqXJgShfig2jPT11QDl0eHzI0Ux8vc1luJT+qZ/EiaMwIDAQAB

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tuanht022@gmail.com
spring.mail.password=wrjx zdnk dyxc tdtu
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

OTP.MAX_RETRY=5
OTP.MAX_RESEND=5
